name: Release Drafter

on:
  push:
    # Only draft releases on the main branch
    branches:
      - $default-branch

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
